version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: andre
      POSTGRES_PASSWORD: qwepoi123
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
